/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Employee;
import models.Manutencao;
import models.Mechanic;
import models.Motor;
import models.User;
import models.Vehicle;
import repositories.EmployeeRepository;
import repositories.ManutencaoRepository;
import repositories.MotorRepository;
import repositories.UserRepository;
import repositories.VehicleRepository;
import utils.tables.ManutencaoTableDataTransform;
import utils.tables.TableSerialize;
import utils.tables.UserTableDataTransform;

/**
 *
 * @author nzinga
 */
public class Maintenance extends javax.swing.JPanel {

    /**
     * Creates new form Maintenance
     */
    public Maintenance() {
        initComponents();
        
        
        loadManutencaoData();
    
        try {
             ArrayList<Mechanic> mechanicList = new ArrayList<Mechanic>();
             ArrayList<Employee> employeeList = EmployeeRepository.getAll();
             ArrayList<Vehicle> vehicleList = VehicleRepository.getAll();
             ArrayList<Motor> motorList = MotorRepository.getAll();
             //ArrayList<manutencao> manutencaoList = 
             
            

             
           for(int i = 0; i < employeeList.size(); i++) {
                 Employee employee = employeeList.get(i);
                 if(employee.getOffice().compareTo("Mecânico") == 0){
                     String bi = employee.getBi();
                     String firstName = employee.getFirstName();
                     String lastName = employee.getLastName();
                     String nacionality = employee.getNacionality();
                     String office = employee.getOffice();
                     Date birthDate = employee.getBirthDate();
                     
                     char  sex = employee.getSex();
                     Mechanic mechanic = new Mechanic(bi,firstName,lastName,nacionality,sex,birthDate,office);
                     mechanicList.add(mechanic);
                 }
             }
        
             
             int mechanicLength = mechanicList.size();
             int vehicleLength = vehicleList.size();
             int motorlength = motorList.size();
            String mechanicData[] = new String[mechanicLength];
            String vehicleData[] = new String[vehicleLength];
            String motorData[] = new String[motorlength];
            
            for (int i = 0; i < mechanicLength; i++) {
                mechanicData[i] = mechanicList.get(i).getFirstName() + " " + mechanicList.get(i).getLastName();
             }
            for (int i = 0; i < vehicleLength; i++) {
                vehicleData[i] = vehicleList.get(i).getModel() + "-" + vehicleList.get(i).getBrand();
            }
            for (int i = 0; i < motorlength; i++) {
                motorData[i] = motorList.get(i).getBrand() + "-" + motorList.get(i).getModel() + "-" + motorList.get(i).getCilinder();
            }
            
            employeeCd.setModel(new DefaultComboBoxModel(mechanicData));
            vehicleM.setModel(new DefaultComboBoxModel(vehicleData));
            //manutencao_motor.setModel(new DefaultComboBoxModel(motorData)); 
             
        
        } catch (Exception e) {
            System.out.println("Erro ao carregar Funcionário");
            
        }
        
       
    }

   /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
    */ 
     
    ArrayList<Manutencao> manutencaoList;
    @SuppressWarnings("unchecked")
    
    private void loadManutencaoData() {
        try {
            manutencaoList = ManutencaoRepository.getAll();
            String [][] data = ManutencaoTableDataTransform.dataTransform(manutencaoList);
            System.out.println(data[0][0]);
            String [] columnNames = ManutencaoTableDataTransform.dataColumn();
            TableSerialize manutencaoTableModel = new TableSerialize(data, columnNames) ;
            manutencaoTb.setModel(manutencaoTableModel);
        } catch (Exception e) {

        }
    }
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        employeeCd = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        descricaotxt = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        manutencao_motor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        vehicleM = new javax.swing.JComboBox<>();
        spinnerCusto = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manutencaoTb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Tipo");

        comboTipo.setBackground(new java.awt.Color(227, 236, 245));
        comboTipo.setForeground(new java.awt.Color(140, 164, 188));
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha tipo", "Parcial", "Completa" }));

        jLabel3.setText("Descrição");

        jLabel4.setText("Custos");

        jLabel6.setText("Funcionário");

        employeeCd.setBackground(new java.awt.Color(227, 236, 245));
        employeeCd.setForeground(new java.awt.Color(140, 164, 188));
        employeeCd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha funcionário" }));

        jButton1.setBackground(new java.awt.Color(55, 66, 88));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        descricaotxt.setBackground(new java.awt.Color(227, 236, 245));
        descricaotxt.setColumns(20);
        descricaotxt.setForeground(new java.awt.Color(140, 164, 188));
        descricaotxt.setRows(5);
        jScrollPane2.setViewportView(descricaotxt);

        jLabel8.setText("Estado da Manutencao");

        manutencao_motor.setBackground(new java.awt.Color(227, 236, 245));
        manutencao_motor.setForeground(new java.awt.Color(140, 164, 188));
        manutencao_motor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em andamento", "Concluido" }));
        manutencao_motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manutencao_motorActionPerformed(evt);
            }
        });

        jLabel9.setText("Veículos");

        vehicleM.setBackground(new java.awt.Color(227, 236, 245));
        vehicleM.setForeground(new java.awt.Color(140, 164, 188));
        vehicleM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolhe veículo" }));
        vehicleM.setMinimumSize(new java.awt.Dimension(138, 28));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeCd, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(manutencao_motor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vehicleM, 0, 252, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(manutencao_motor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeCd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Cadastrar", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        manutencaoTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Componentes dpo veículo", "Custo", "Estado", "Funcionário", "Veículo", "Descrição"
            }
        ));
        jScrollPane1.setViewportView(manutencaoTb);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jPanel2);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(55, 66, 88));
        jLabel1.setText("Manutenção");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String tipo = (String) comboTipo.getSelectedItem();
            String estado = (String) manutencao_motor.getSelectedItem();
            int custo = (int) spinnerCusto.getValue();
            int veiculo = vehicleM.getSelectedIndex();
            int empregado = employeeCd.getSelectedIndex();
            String desc = descricaotxt.getText();
            int id = 1;
            
        
            Manutencao manut = new Manutencao(tipo, desc, custo, empregado, veiculo);
            //Manutencao manut = new Manutencao(1, "parcial", "descricao", 120, 1,1);
             
            
             try {
                ManutencaoRepository.add(manut);
                JOptionPane.showMessageDialog(null, " Manutencao feita com sucesso");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao fazer manutencao "+ ex);
            }
            loadManutencaoData();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void manutencao_motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manutencao_motorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manutencao_motorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JTextArea descricaotxt;
    private javax.swing.JComboBox<String> employeeCd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable manutencaoTb;
    private javax.swing.JComboBox<String> manutencao_motor;
    private javax.swing.JSpinner spinnerCusto;
    private javax.swing.JComboBox<String> vehicleM;
    // End of variables declaration//GEN-END:variables
}
